const ModelTypes = {
  GRAPHQL: "GRAPHQL",
  JSON: "JSON",
  MARIADB: "MARIADB",
  MONGODB: "MONGODB",
  MONGOOSE: "MONGOOSE",
  MYSQL: "MYSQL",
  PG: "PG",
  SEQUELIZE: "SEQUELIZE",
  SQLITE: "SQLITE",
  LOGICAL: "LOGICAL",
  JSONSCHEMA: "JSONSCHEMA",
  OPENAPI: "OPENAPI",
  FULLJSON: "FULLJSON"
};

module.exports = ModelTypes;
